In [1]:
# Manipulação e análise de dados
import pandas as pd
import numpy as np

In [2]:
# Carregendo o dataset do tipo csv
df = pd.read_csv('v.csv', sep=',', encoding='utf-8')

In [3]:
#FASE 1: DIAGNÓSTICO INICIAL (Apenas Observação - SEM Modificações)

In [7]:
# Verificar dimensões (linhas e colunas)
df.shape

(1000, 10)

In [9]:
# Verificar tipos de dados
df.dtypes

id_venda          int64
data             object
cliente          object
categoria        object
canal            object
uf               object
quantidade        int64
preco_unit       object
desconto_pct     object
valor_total     float64
dtype: object

In [11]:
# Verificar memória usada
df.memory_usage(deep=True)

Index             132
id_venda         8000
data            59000
cliente         57063
categoria       56595
canal           48915
uf              47142
quantidade       8000
preco_unit      48902
desconto_pct    48474
valor_total      8000
dtype: int64

In [13]:
# Primeiras linhas
df.head()

,id_venda,data,cliente,categoria,canal,uf,quantidade,preco_unit,desconto_pct,valor_total
0,1,2024-08-08,CLI-0069,Limpeza,NaN,BA,1,NaN,0.45,50.63
1,2,2024-11-12,CLI-0050,Limpeza,Loja,RJ,4,111.06,4.91,422.43
2,3,2024-09-08,CLI-0149,Padaria,Loja,NaN,5,10.73,4.86,5104.00
3,4,2024-04-07,CLI-0044,Bebidas,NaN,SP,2,87.89,2.87,170.74
4,5,2024-06-27,CLI-0140,Hortifruti,Loja,SP,1,8.10,NaN,8.07

In [15]:
# IDENTIFICAÇÃO DE DADOS NULOS

In [17]:
#Contar nulos por coluna
df.isnull().sum()

id_venda          0
data              0
cliente           0
categoria         0
canal           200
uf              208
quantidade        0
preco_unit      224
desconto_pct    217
valor_total       0
dtype: int64

In [19]:
# Calcular percentual de nulos por coluna
(df.isnull().sum() / len(df)) * 100

id_venda         0.0
data             0.0
cliente          0.0
categoria        0.0
canal           20.0
uf              20.8
quantidade       0.0
preco_unit      22.4
desconto_pct    21.7
valor_total      0.0
dtype: float64

In [21]:
# Identificar colunas com mais de 50% de nulos
df.columns[df.isnull().sum() > len(df) * 0.5].tolist()

[]

In [23]:
# Visualizar padrão de nulos
df.isnull()

,id_venda,data,cliente,categoria,canal,uf,quantidade,preco_unit,desconto_pct,valor_total
0,False,False,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,True,True,False
997,False,False,False,False,False,True,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,True,False

In [25]:
# ANÁLISE INICIAL DE QUALIDADE

In [27]:
# Verificar duplicatas completas
df.duplicated().sum()

0

In [29]:
df[df['quantidade'] == 5][['id_venda', 'cliente', 'valor_total']].sort_values('valor_total', ascending=False).head(5)

     id_venda    cliente  valor_total
2           3   CLI-0149      5104.00
155       156   CLI-0004      1102.86
904       905   CLI-0096       811.25
214       215  CLI-0013        773.74
524       525   CLI-0201       687.92

In [31]:
# Verificar duplicatas por ID
df['id_venda'].duplicated().sum()

0

In [33]:
# Resumo estatístico básico
df.describe()

          id_venda   quantidade  valor_total
count  1000.000000  1000.000000  1000.000000
mean    500.500000     2.649000   133.320190
std     288.819436     2.038125   412.988488
min       1.000000     1.000000     1.480000
25%     250.750000     1.000000    12.840000
50%     500.500000     2.000000    42.345000
75%     750.250000     3.000000   136.560000
max    1000.000000    12.000000  9468.000000

In [35]:
#Informações gerais (info substituto)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_venda      1000 non-null   int64
 1   data          1000 non-null   object
 2   cliente       1000 non-null   object
 3   categoria     1000 non-null   object
 4   canal         800 non-null    object
 5   uf            792 non-null    object
 6   quantidade    1000 non-null   int64
 7   preco_unit    776 non-null    object
 8   desconto_pct  783 non-null    object
 9   valor_total   1000 non-null   float64
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB

In [37]:
# ANÁLISE E TRATAMENTO - COLUNA 'preco_unit' (NUMÉRICA)

In [39]:
#Contar nulos
df['preco_unit'].isna().sum()

224

In [41]:
# Converter para float
df['preco_unit'] = pd.to_numeric(df['preco_unit'], errors='coerce')

In [43]:
#Calcular média (para preenchimento)
media_preco = df['preco_unit'].mean()
print(f"Média de preço_unit: {media_preco:.2f}")

Média de preço_unit: 44.14

In [45]:
#Preencher nulos com média
#df['preco_unit'].fillna(df['preco_unit'].mean(), inplace=True) # deu errado essa mensagem:  

# FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
# The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting
# values always behaves as a copy.

# For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)'
# or df[col] = df[col].method(value) instead,
# to perform the operation inplace on the original object.

# df['preco_unit'].fillna(df['preco_unit'].mean(), inplace=True)

In [47]:
# Preencher nulos com média
df['preco_unit'] = df['preco_unit'].fillna(df['preco_unit'].mean())

In [49]:
# ANÁLISE E TRATAMENTO - COLUNA 'desconto_pct' (NUMÉRICA)

In [51]:
# Contar nulos
df['desconto_pct'].isna().sum()

217

In [53]:
# Converter para float
df['desconto_pct'] = pd.to_numeric(df['desconto_pct'], errors='coerce')

In [55]:
# Calcular mediana (para preenchimento)
mediana_desconto = df['desconto_pct'].median()
print(f"Mediana de desconto_pct: {mediana_desconto:.2f}")

Mediana de desconto_pct: 1.90

In [57]:
# Preencher nulos com mediana
#df['desconto_pct'].fillna(df['desconto_pct'].median(), inplace=True)
df['desconto_pct'] = df['desconto_pct'].fillna(df['desconto_pct'].median())

In [68]:
# ANÁLISE E TRATAMENTO - COLUNA 'quantidade' (NUMÉRICA)

In [71]:
#Verificar se tem nulos
df['quantidade'].isna().sum()

0

In [73]:
# Validar que não há valores zero ou negativos
(df['quantidade'] <= 0).sum()

0

In [ ]:
# ANÁLISE E TRATAMENTO - COLUNA 'canal' (TEXTO)

In [75]:
# Contar nulos
df['canal'].isna().sum()

200

In [77]:
# Verificar valores únicos
df['canal'].unique()

array([nan, 'Loja', 'App', 'Site', '--', 'Televendas', 'sem informacao',
       'APP', '?', '-', 'App ', 'LOJA', 'loja', '  App ', 'site', 'null ',
       '  Loja ', '  Site ', 'Televendas ', 'app', 'SITE', 'Loja ',
       'Site ', '  Televendas '], dtype=object)

In [79]:
# Contar frequência de cada valor
df['canal'].value_counts()

canal
Loja              330
Site              199
App               169
Televendas         36
-                  11
sem informacao      9
?                   9
App                 4
SITE                4
  Loja              4
  Site              3
--                  3
APP                 3
  App               3
Site                2
Loja                2
loja                2
site                2
Televendas          1
app                 1
null                1
LOJA                1
  Televendas        1
Name: count, dtype: int64

In [85]:
# Preencher nulos com moda (valor mais frequente)
moda_canal = df['canal'].mode()[0]
#df['canal'].fillna(moda_canal, inplace=True)
df['canal'] = df['canal'].fillna(moda_canal)